### ISSUE TITLE
Unauthenticated packages and package keys

### ISSUE THREAD

**Issue by TheAssassin** [nomad-desktop/nxos-docker-image#2]
https://github.com/nomad-desktop/nxos-docker-image/blob/f7398c2af6f502607f58179afba9f2fe69385459/Dockerfile#L5-10

See https://github.com/nomad-desktop/nx-software-center/issues/20. Flags like `--allow-unauthenticated` are nothing you should use frivolously.

Also, the keys are not authenticated (neither via HTTPS (authentication of origin server) nor by authenticating the file itself (e.g., comparing the file with a known hash hardcoded in the Dockerfile).
Given that the keys will be used for future package updates inside the container, this is a really critical issue (in comparison to the software center issue).

**Comment by TheAssassin** [comment]
Preparing a PR fixing the issues.

**Comment by luis-lavaire** [comment]
I just copy-pasted the command for RUN. Didn't checked.

**Comment by TheAssassin** [comment]
I will push the PR as soon as the build succeeds once on my (always crowded) workstation. It's been running for maybe an hour already...
