### ISSUE TITLE
Purpose of start.sh?

### ISSUE THREAD

**Issue by TheAssassin** [nomad-desktop/nxos-docker-image#3]
This Docker image is supposed to be a generic image to be used for other purposes. I can't imagine why there should be a `start.sh` script in such a base image.

Ubuntu images specify `/bin/bash` as `CMD`. I wouldn't change that for a base image.

**Comment by luis-lavaire** [comment]
The purpose is that it becomes a wrapper that prepares the environment before the build process. I'm not completely sure that we really need it, but in case we do...

**Comment by TheAssassin** [comment]
Build process...? I thought this repository was about building a Docker base image for other purposes.

Workflow: a base image, e.g., `nxos/nxos` is built using this repository. Then, for e.g., building purposes, if modifications are needed, a derivative image based on `nxos/nxos` is built.

**Comment by luis-lavaire** [comment]
Well, the idea behind this image is providing an environment suitable for building applications we make for NXOS, like the software center, the updater, babe, etc. So there's where `start.sh` appears.

But, of course we could use `/bin/[ba]sh` in order to provide a more generic image.

**Comment by TheAssassin** [comment]
For builds on the new class CI systems, like Travis, where you have to run the Docker image using `docker run` calls, a start script shouldn't be required.

For systems like Jenkins or Gitlab CI, where the Docker image is pulled and run to have an agent within the container connect to the server, you may need a start script, although I believe at least the Jenkins Docker plugin overwrites the command itself.

A generic nxos image would be great, as it allows building derivatives for all these purposes.

**Comment by azubieta** [comment]
Well for building we need an image with all the building stuff: gcc, qt, kf5-frameworks, plasma-frameworks, cmake and git.

But also for testing purposes we don't need anything of it, only a bare nxos system.

So what if we create two images?

**Comment by TheAssassin** [comment]
That's the idea, @azubieta.

By the way, regarding #4, for a "base image" I'd say adding the repositories and running `apt-get dist-upgrade` should suffice, the amount of packages pulled in at the moment is _huge_.

**Comment by luis-lavaire** [comment]
Agree. So let's work on a basic image. @azubieta and I will then add the stuff we need for building our apps.
