### ISSUE TITLE
Build and publish in public registry

### ISSUE THREAD

**Issue by TheAssassin** [nomad-desktop/nxos-docker-image#5]
The image should be published in a public registry. I suggest `nxos/nxos` as a name.

I personally use https://quay.io, but I think it makes more sense to offer this kind of image on Docker Hub.

**Comment by TheAssassin** [comment]
Just for fun, I set up https://quay.io/repository/nxos/nxos?tab=tags.

**Comment by luis-lavaire** [comment]
Image will be pushed to [docker hub](https://hub.docker.com/r/luislavaire/nxos/).

**Comment by TheAssassin** [comment]
@luis-lavaire would you consider registering an organization, e.g., `nxos`? Now, it doesn't look like anything official.

**Comment by luis-lavaire** [comment]
@TheAssassin now we have an organization for it: https://hub.docker.com/r/nxos/nxos/.

**Comment by TheAssassin** [comment]
Awesome.
